### ISSUE TITLE
Develop list of supported editors for ASCIIDOC

### ISSUE THREAD

**Issue by kersten1** [riscv-admin/docs-sig#19]
Provide a list of editors that people can use to develop specs with some guidelines.

**Comment by kersten1** [comment]
Can borrow or link to this - https://github.com/bodiam/awesome-asciidoc

**Comment by kbroch-rivosinc** [comment]
> Can borrow or link to this - https://github.com/bodiam/awesome-asciidoc

Unfortunately there's a lot of bit rot (I've found at least three 404 errors) since the repo hasn't been updated in 4+ years.
