### ISSUE TITLE
Look at ASCIIDoc extension to list tables and figures

### ISSUE THREAD

**Issue by kersten1** [riscv-admin/docs-sig#25]

**Comment by kbroch-rivosinc** [comment]
I tested it out manually and it WAI.

PR to add it to the docker image: https://github.com/riscv/riscv-docs-base-container-image/pull/6

**Comment by wmat** [comment]
Is that extension good enough?

I had intended on implementing this one: https://gitlab.com/baiyibai/asciidoctor-pdf-lofte which adheres the asciidoctor-pdf's TOC formatting and is also style-able.

**Comment by kbroch-rivosinc** [comment]
I wasn't aware of this other plugin.  My hope was we'd find something that worked with both pdf and html output. 

This one does: https://github.com/Alwinator/asciidoctor-lists but I do see that it has some features missing that we might care about (pg number on list?) and the pdf styling may not be honored.

I'll take a look at both and let you know.

**Comment by kbroch-rivosinc** [comment]
## asciidoctor-lists 
using latest release: https://github.com/Alwinator/asciidoctor-lists/releases/tag/v1.0.9
I used [this spec](https://github.com/riscv/riscv-cfi/compare/main...kbroch-rivosinc:riscv-cfi:dev/kbroch/try-asciidoctor-lists-plugin) to test.

HTML output :
![image](https://github.com/riscv-admin/docs-sig/assets/86068473/5d5aebea-7015-4069-9752-be7b503f3602)

PDF output:
![image](https://github.com/riscv-admin/docs-sig/assets/86068473/3bf2b313-863b-4696-838b-d61ebd28c9f3)

Findings:
- both pdf and html output appears to use the theme's styling correctly
-  listing is not capable of rendering the "code" backtick text correctly.  Instead just leaves tags. ex: <code>memvcfg</code>

## asciidoctor-pdf-lofte
using the latest release: [asciidoctor-pdf-lofte](https://gitlab.com/baiyibai/asciidoctor-pdf-lofte/-/tree/main)

Here's branch of changes to example spec: https://github.com/kbroch-rivosinc/riscv-cfi/tree/dev/kbroch/try-asciidoctor-pdf-lofte


![image](https://github.com/riscv-admin/docs-sig/assets/86068473/fc93d396-ae4f-4075-98a6-ba8cd043f5c8)


Findings:
- doesn't package code into gem, you simple have to download the unversioned ruby file
- pdf output appears to use the theme's styling correctly
- anchors have to be added to everything or no list items are generated (NOTE: I didn't add all of them)
- doesn't support HTML output at all
- the "List of Listings" comes after the "Preamble"?

## My recommendation

Given `asciidoctor-lists` supports styling of themes, both pdf/html outputs, and is packaged as a gem for easy installation and maintenance, I would recommend using that.  I'll file an issue on the back-tick code block not getting rendered in the title.

**Comment by kbroch-rivosinc** [comment]
Filed issue on `backtick literal` not rendered: https://github.com/Alwinator/asciidoctor-lists/issues/23

**Comment by wmat** [comment]
Thanks @kbroch-rivosinc I agree, we should move forward with asciidoctor-lists for now.

**Comment by kbroch-rivosinc** [comment]
> Filed issue on `backtick literal` not rendered: [Alwinator/asciidoctor-lists#23](https://github.com/Alwinator/asciidoctor-lists/issues/23)

This works fine if  ` list-of::image[enhanced_rendering=true]` is used: 
![Screenshot 2024-04-23 6 22 58 AM](https://github.com/riscv-admin/docs-sig/assets/86068473/70461468-c916-4167-b4ae-36d8648eea60)

I can imagine wanting to use both of these parameters: `list-of::image[hide_empty_section=true, enhanced_rendering=true]`

**Comment by kbroch-rivosinc** [comment]
The only other feature  I can see wanting currently is page numbers: https://github.com/Alwinator/asciidoctor-lists/issues/14.
The maintainer of asciidoctor-pdf-lofte was also in this issue discussion (and zulipchat) but it doesn't look like it has progressed past that in over a year.

**Comment by wmat** [comment]
Lists of Tables/List of Figures has been raised as a possible addition to Unpriv and Priv.  See https://github.com/riscv/riscv-isa-manual/issues/1532

I have created a Branch from that issue and added Lof/Lot to Priv and Unpriv there.  Note that only figures & tables with captions get picked up, which makes sense as asciidoctor needs to populate the list with some text.  I have opened a discussion with Andrew W. in that issue for thoughts on moving forward.  You can also either grab PDFs with the lists included from the Actions tab here https://github.com/riscv/riscv-isa-manual/actions/runs/9940634186 or run the Build ISAs action against that branch.

**Comment by kersten1** [comment]
I think that this was finally voted down. It is possible, but decided to not be implemented.
