### ISSUE TITLE
Listings caption

### ISSUE THREAD

**Issue by ved-rivos** [riscv-admin/docs-sig#40]
The listings in the ISA specification are captioned as "Example". While some of the listings are examples, many others are not. For instance, the below listing is to provide pseudocode for the `LPAD` instruction. This seems to be an issue only with the ISA manual build scripts. When building this code using build scripts in the CFI GitHub, the caption is generated as "Listing". How can we annotate the code to produce the correct caption @wmat @kersten1 @kbroch-rivosinc  ?

```
.`LPAD` operation
[listing]
----
if (xLPE == 1 && ELP == LP_EXPECTED)
    // If PC not 4-byte aligned then software-check exception
    if pc[1:0] != 0
        raise software-check exception
    // If landing pad label not matched -> software-check exception
    else if (inst.LPL != x7[31:12] && inst.LPL != 0)
        raise software-check exception
    else
        ELP = NO_LP_EXPECTED
else
    no-op
endif
----
```
As rendered in ISA manual PDF:
![image](https://github.com/riscv-admin/docs-sig/assets/91900059/94be2b29-43d4-4aea-a504-827ea7038283)

As rendered in CFI standalone spec PDF:
![image](https://github.com/riscv-admin/docs-sig/assets/91900059/c3f49fbd-287d-4a73-8f23-7b006e0d93ef)

**Comment by kbroch-rivosinc** [comment]
In general, there are several types of "prefixed caption labels" https://docs.asciidoctor.org/asciidoc/latest/blocks/add-title/#captioned-titles for different block types.  

For your specific example: https://github.com/riscv/riscv-isa-manual/blob/2d1a43e653400c139de7a77b7c4c13e13b83bd26/src/riscv-privileged.adoc?plain=1#L34

The cfg changed from `:listing-caption: Listing` to `:listing-caption: Example`  when going from individual spec. to isa manual.

I think for specs moving forward we need to define all these to something like:

```
:appendix-caption: Appendix
:example-caption: Example
:figure-caption: Figure
:listing-caption: Listing
:table-caption: Table
```

One question is what's the difference between an "example" vs. "listing" (ie: code)?  

Whatever that answer it should be made clear in the https://github.com/riscv/docs-dev-guide and have examples of  various block types and the standard uses of them.  Also this needs to be considered for the "Lists of Lists" in the TOC.
(currently I didn't put in a "List of Examples")

**Comment by ved-rivos** [comment]
> One question is what's the difference between an "example" vs. "listing" (ie: code)?

Example would be a code sequence to illustrate and example of how an instruction would be used.

In my example, the listing was the the pseudocode describing the instructions behavior. So one option would be to have "Algorithm" or "Pseudocode" as a caption.

I would like to fix this in the isa-manual for the control-flow integrity chapter. Please help.

**Comment by ved-rivos** [comment]
Thanks!
