### ISSUE TITLE
Exclude .svg files from lint checks

### ISSUE THREAD

**Issue by ved-rivos** [riscv-admin/docs-sig#51]
**Describe your idea.**
The build scripts do various checks like "no newline" on .svg files. SInce these are not human readable files, files of this type could be excluded.

**Describe why it is important**
A clear and concise description of what this will solve

**Additional context**

**Comment by kbroch-rivosinc** [comment]
Yes I should have done this for recent PR in iommu.  Here's new PR: https://github.com/riscv-non-isa/riscv-iommu/pull/347

general docs for this here: https://pre-commit.com/index.html#hooks-exclude

**Comment by ved-rivos** [comment]
Thanks!
